name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch Strapi Data
        run: |
          mkdir -p data # Ensure the data directory exists
          curl -X GET "https://fortunate-nest-b13a1e6068.strapiapp.com/api/people?populate=*" \
               -H "Authorization: Bearer ${{ secrets.STRAPI_API_TOKEN }}" \
               -o data/strapi_people_with_images.json
        env:
          STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }} # Make the secret available as an environment variable

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      # --- NEW DEBUGGING STEP IS HERE ---
      - name: List files in public directory
        run: ls -R public
      # --- END OF NEW STEP ---

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
